import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import localFont from 'next/font/local'
import MainTheme from "./theme/MainTheme";
const bYekan = localFont({
  variable: '--font-bYekan',
  src: "../public/BYekan.woff2",
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${bYekan.className}`}>
      <body>
        <AppRouterCacheProvider options={{ key: 'css' }}>
          <MainTheme>
            {children}
          </MainTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
