import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import MainTheme from "./theme/MainTheme";
import { StoreProvider } from "./store/StoreProvider";
import Header from "./components/Header";
const dosis = Dosis({
  variable: "--font-geist-dosis",
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html className={`${dosis.className}`}>
        <body>
          <AppRouterCacheProvider options={{ key: 'css' }}>
            <MainTheme>
              <Header />
              {children}
            </MainTheme>
          </AppRouterCacheProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
